# Azure Pipeline to deploy Logging Infrastructure (Workspace + Automation)
# This pipeline deploys the logging Bicep template as a Deployment Stack at subscription scope

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - code/bicep/logging/**
      - code/pipelines/logging/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - code/bicep/logging/**
      - code/pipelines/logging/**

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - group: monitoring-variables # Reusing for subscription ID which is likely same
  - name: bicepPath
    value: "code/bicep/logging"
  - name: templateFile
    value: "$(bicepPath)/logging.bicep"
  - name: parametersFile
    value: "$(bicepPath)/logging.bicepparam"
  - name: scriptsPath
    value: "code/pipelines/logging"
  - name: stackName
    value: "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}"

parameters:
  - name: projectName
    displayName: "Project Name"
    type: string
    default: "landing-zone"
  - name: workloadAlias
    displayName: "Workload Alias"
    type: string
    default: "logging"
  - name: environment
    displayName: "Environment"
    type: string
    default: "live"
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 01 for the first instance)"
    type: string
    default: "01"
  - name: location
    displayName: "Azure Region"
    type: string
    default: "canadacentral"

  # ============================================================================
  # CONFIGURATION
  # ============================================================================
  - name: dataRetention
    displayName: "Data Retention (days, 30-730)"
    type: number
    default: 60
  - name: dailyQuotaGb
    displayName: "Daily Quota (GB, -1 for unlimited)"
    type: number
    default: -1

  # ============================================================================
  # OWNERSHIP
  # ============================================================================
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "$(managedBy)"
  - name: owner
    displayName: "Owner"
    type: string
    default: "$(defaultOwner)"

  # ============================================================================
  # DEPLOYMENT STACK SETTINGS
  # ============================================================================
  - name: denySettingsMode
    displayName: "Deny Settings Mode"
    type: string
    default: "denyWriteAndDelete"
    values:
      - none
      - denyDelete
      - denyWriteAndDelete
  - name: actionOnUnmanage
    displayName: "Action on Unmanaged Resources"
    type: string
    default: "detachAll"
    values:
      - deleteResources
      - deleteAll
      - detachAll
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "Preview"
    values:
      - Validation
      - Preview
      - Deploy
      - Remove

stages:
  - stage: Validate
    displayName: "Validate Deployment Stack"
    jobs:
      - template: ../templates/jobs/validate-environment-job.yaml
        parameters:
          environment: ${{ parameters.environment }}
      - job: ValidateStack
        displayName: "Validate Stack"
        dependsOn: ValidateEnvironment
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate Logging Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                bash $(scriptsPath)/logging-validate-stack.sh \
                  "$(monitoringSubscriptionId)" \
                  "$(templateFile)" \
                  "$(parametersFile)" \
                  "$(deploymentLocation)" \
                  "$(stackName)" \
                  "${{ parameters.denySettingsMode }}" \
                  "${{ parameters.actionOnUnmanage }}" \
                  "${{ parameters.projectName }}" \
                  "${{ parameters.workloadAlias }}" \
                  "${{ parameters.environment }}" \
                  "${{ parameters.locationCode }}" \
                  "${{ parameters.instanceNumber }}" \
                  "${{ parameters.location }}" \
                  "${{ parameters.dataRetention }}" \
                  "${{ parameters.dailyQuotaGb }}" \
                  "${{ parameters.owner }}" \
                  "${{ parameters.managedBy }}"

  - stage: Preview
    displayName: "Preview Stack State"
    dependsOn: Validate
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'Preview', 'Deploy')
      )
    jobs:
      - job: PreviewStack
        displayName: "Preview Stack"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Preview Stack State"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                bash $(scriptsPath)/logging-preview-stack.sh \
                  "$(monitoringSubscriptionId)" \
                  "$(stackName)"

  - stage: Deploy
    displayName: "Deploy Logging Deployment Stack"
    dependsOn:
      - Validate
      - Preview
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.Preview.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeployLoggingStack
        displayName: "Deploy Logging Stack"
        environment: "${{ parameters.environment }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy Logging Deployment Stack"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      bash $(scriptsPath)/logging-deploy-stack.sh \
                        "$(monitoringSubscriptionId)" \
                        "$(templateFile)" \
                        "$(parametersFile)" \
                        "$(deploymentLocation)" \
                        "$(stackName)" \
                        "${{ parameters.denySettingsMode }}" \
                        "${{ parameters.actionOnUnmanage }}" \
                        "${{ parameters.projectName }}" \
                        "${{ parameters.workloadAlias }}" \
                        "${{ parameters.environment }}" \
                        "${{ parameters.locationCode }}" \
                        "${{ parameters.instanceNumber }}" \
                        "${{ parameters.location }}" \
                        "${{ parameters.dataRetention }}" \
                        "${{ parameters.dailyQuotaGb }}" \
                        "${{ parameters.owner }}" \
                        "${{ parameters.managedBy }}"

  - stage: Remove
    displayName: "Remove Logging Deployment Stack"
    dependsOn: Validate
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        eq('${{ parameters.deploymentStage }}', 'Remove')
      )
    jobs:
      - deployment: RemoveLoggingStack
        displayName: "Remove Logging Stack"
        environment: "${{ parameters.environment }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Delete Logging Deployment Stack"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      bash $(scriptsPath)/logging-delete-stack.sh \
                        "$(monitoringSubscriptionId)" \
                        "$(stackName)" \
                        "${{ parameters.actionOnUnmanage }}"
